###
POST http://localhost:4000/proveedor/proveedores HTTP/1.1
Content-Type: application/json

{
    "nombre": "aaa",
    "apellido": "bbb",
    "codigo": 1,
    "nit": 1,
    "departamento": "ccc",
    "municipio": "ddd",
    "correo": "eee",
    "telefono": 1 
}

###
GET http://localhost:4000/proveedor/proveedores HTTP/1.1

###
GET http://localhost:4000/proveedor/proveedores/66141e310685ce436f5105b3 HTTP/1.1

###
PUT http://localhost:4000/proveedor/proveedores/ HTTP/1.1
Content-Type: application/json

{
    "nombre": "",
    "apellido": "",
    "codigo": 0,
    "nit": 0,
    "departamento": "",
    "municipio": "",
    "correo": "",
    "telefono": 0 
}

###
DELETE http://localhost:4000/proveedor/proveedores/6611bc07c5ff930a23e461b6 HTTP/1.1
